# Build Configuration
[[build]]
  name = "Go Build"
  builder = "nixpacks"
  # Command for installing dependencies
  command = "go mod download"
  # Directory
  root = "Server"

# Deploy Configuration
[[deploy]]
  name = "Go Deploy"
  command = "./Server"
  replicas = 1